spring.datasource.url=jdbc:mysql://localhost:3306/GymManagement
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
##spring.sql.init.schema-locations=classpath:sql/schema.sql
##spring.sql.init.data-locations=classpath:sql/data.sql

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8084